const API = `https://jsonplaceholder.typicode.com/todos`;

const TODOS_FILTER_ALL = `TODOS_FILTER_ALL`;
const TODOS_FILTER_COMPLETED = `TODOS_FILTER_COMPLETED`;
const TODOS_FILTER_PROGRESS = `TODOS_FILTER_PROGRESS`;

const TODOS_COLOR = '#000000';

export { API, TODOS_FILTER_ALL, TODOS_FILTER_COMPLETED, TODOS_FILTER_PROGRESS, TODOS_COLOR }